import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * One entry per constitutional paragraph touched by the regionalization
 * amendment. Everything except `summary` and `whatChanged` is generated by
 * scripts/extract-amendments.py and must not be hand-edited.
 *
 * `sources` is required and non-empty on purpose: an unsourced paragraph
 * should fail the build rather than render as though it were established.
 * Same rule the Denominations schema enforces.
 */
const paragraphs = defineCollection({
  loader: glob({ pattern: "*.yaml", base: "./src/content/paragraphs" }),
  schema: z.object({
    ballotNumber: z.number().int(),
    disciplineNumber: z.number().int(),
    status: z.enum(["amended", "new", "deleted"]),

    articleOld: z.string(),
    articleNew: z.string(),
    sectionOld: z.string(),
    sectionNew: z.string(),
    divisionOld: z.string(),

    /** Share of the prior wording surviving. Report, not confidence. */
    retainedWording: z.number().min(0).max(1),
    /** The amendment rewrote rather than tweaked this paragraph. */
    rewritten: z.boolean(),
    /** The ballot reproduced only the changed portions of this paragraph. */
    elided: z.boolean(),

    textOld: z.string(),
    textNew: z.string(),

    notes: z.array(z.string()).default([]),
    sources: z.array(z.string()).min(1),

    /** Editorial. Absent renders as a stated gap, never as silence. */
    summary: z.string().optional(),
    whatChanged: z.string().optional(),
  }),
});

export const collections = { paragraphs };
